ARG POSTGRESQL_VERSION

FROM postgres:$POSTGRESQL_VERSION

ENV POSTGRES_PASSWORD=postgres

COPY healthcheck.sh /usr/local/bin/

RUN chmod u+x /usr/local/bin/healthcheck.sh
RUN echo max_prepared_transactions = 16 >> /usr/share/postgresql/postgresql.conf.sample

HEALTHCHECK --interval=5s --timeout=60s CMD ["healthcheck.sh"]
