os:
  - windows
  - linux

language: shell

stages:
  - name: test
  - name: deploy
    if: os = linux

jobs:
  include:
    - stage: test
      script: bash build.sh
    - stage: deploy
      script: bash manifest.sh
