os:
  - windows
  - linux

language: shell

stages:
  - name: build
  - name: deploy
    if: os = linux

jobs:
  include:
    - stage: build
      script: bash build.sh
    - stage: deploy
      script: bash manifest.sh
