FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    gnupg2

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install -y \
    unzip \
    zip \
    git \
    nodejs \
    yarn
