ARG VERSION

FROM postgres:$VERSION

ENV POSTGRES_PASSWORD=postgres

COPY healthcheck.sh /usr/local/bin/

RUN chmod u+x /usr/local/bin/healthcheck.sh

HEALTHCHECK --interval=5s --timeout=60s CMD ["/usr/local/bin/healthcheck.sh"]
