ARG VERSION

FROM postgres:$VERSION

ENV POSTGRES_PASSWORD=postgres

COPY healthcheck.sh /usr/local/bin/

RUN chmod u+x /usr/local/bin/healthcheck.sh
RUN echo max_prepared_transactions = 16 >> /var/lib/postgresql/data/postgresql.conf

HEALTHCHECK --interval=5s --timeout=60s CMD ["healthcheck.sh"]
