name: postgres

on: [push]

env:
  POSTGRES_VERSION: 12.3-2

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cd postgres
          docker build --build-arg VERSION=$POSTGRES_VERSION --file Dockerfile.windows --tag exivity/postgres:$POSTGRES_VERSION .
          docker tag exivity/postgres:$POSTGRES_VERSION exivity/postgres:latest
      - name: login
        run: echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USER --password-stdin
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: push
        run: |
          docker push exivity/postgres:$POSTGRES_VERSION
          docker push exivity/postgres:latest
