name: postgres

on:
  push:
    paths:
      - "postgres/**"

env:
  IMAGE: postgres
  VERSION: 12.3
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - run: bash build.sh
        env:
          CI_PLATFORM: ${{ matrix.os }}
          EXTRA_BUILD_ARG: 12.3-2

  manifest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: bash manifest.sh
