name: publishDockerImages

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/publishDockerImages.yml"
      - "*.sh"
      - "postgresql/**"

env:
  DOCKER_IMAGE: "satrapu/postgresql"
  POSTGRESQL_VERSION: "15.1"
  DOCKER_HUB_USER: "${{ secrets.DOCKER_HUB_USER }}"
  DOCKER_HUB_TOKEN: "${{ secrets.DOCKER_HUB_TOKEN }}"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]

    env:
      CI_PLATFORM: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - run: bash build.sh
      - run: bash test.sh

  manifest:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - uses: actions/checkout@v1
      - run: bash manifest.sh
